custom_component_validation:
  metadata:
    version: "1.0"
    author: "jard4101"
    compatibility: "Home Assistant 2025.4+ (letzte 4 Versionen)"
    context: "Validierungsregeln für Home Assistant Custom Components (Python-Code, manifest.json, configuration.yaml, Plattformen, Tests)"

  validation_rules:
    code_style:
      - "PEP8-Konformität und Black-Formatierung"
      - "Verwendung von Typannotationen und Docstrings"
      - "Verwendung von Konstanten aus homeassistant.const"
      - "Keine überflüssigen oder veralteten Imports"
      - "Klare Modul- und Klassennamen, keine Namenskonflikte"
      - "Keine toten Codeabschnitte, TODOs oder Debug-Ausgaben im Release"
    manifest_and_requirements:
      - "manifest.json vorhanden und vollständig (name, domain, version, requirements, dependencies, codeowners, config_flow, documentation)"
      - "Alle requirements mit fixer Version (z.B. ['phue==0.8.1'])"
      - "REQUIREMENTS-Konstante im Python-Code nicht mehr verwenden"
      - "Abhängigkeiten und Bibliotheken müssen PyPI- und Lizenz-konform sein"
      - "config_flow muss dokumentiert und getestet sein, falls vorhanden"
      - "Abhängigkeiten, die nicht mehr benötigt werden, entfernen"
    configuration_schema:
      - "Voluptuous-Schema für Konfigurationsprüfung vorhanden"
      - "Alle Konfigurationsoptionen validieren (required/optional, Typen, Wertebereiche, Listen, Entity-IDs, Ports, URLs, Templates etc.)"
      - "Default-Werte für optionale Felder müssen gültig sein (kein None als Default)"
      - "Nur offiziell dokumentierte YAML-Keys und Selektoren verwenden"
      - "PLATFORM_SCHEMA statt CONFIG_SCHEMA für Plattformen verwenden"
      - "Alle Eingaben und Optionen müssen über voluptuous validiert werden (siehe config_validation.py)"
      - "MQTT: valid_subscribe_topic/valid_publish_topic prüfen"
      - "Limits und Choices mit vol.In([]) absichern"
      - "Listen mit ensure_list und Wertprüfung"
      - "Verwendung von homeassistant.const für Standard-Keys"
    integration_quality:
      - "Integration Quality Scale beachten (https://www.home-assistant.io/docs/quality_scale/)"
      - "Tests für alle kritischen Funktionen (unit, integration, snapshot)"
      - "Snapshot-Tests für komplexe Outputs nutzen"
      - "Testabdeckung dokumentieren"
      - "Alle Breaking Changes im Changelog dokumentieren"
      - "Kompatibilität mit aktuellen und vorherigen HA-Versionen testen"
    platform_and_entity:
      - "PLATFORM_SCHEMA korrekt importieren und erweitern"
      - "Entities müssen die richtigen Methoden implementieren (async_update, async_added_to_hass, etc.)"
      - "Datenübergabe über hass.data[DOMAIN] (keine globalen Variablen)"
      - "Dispatcher für Plattform-Kommunikation nutzen (homeassistant.helpers.dispatcher)"
      - "Keine direkte API-Kommunikation im Component-Code (nur über PyPI-Library)"
      - "Alle Entitäten müssen unique_id und device_info unterstützen, falls möglich"
      - "Entitäten müssen async-fähig sein (async def)"
    error_handling_and_logging:
      - "Alle Fehler abfangen und sinnvoll loggen (kein stilles Scheitern)"
      - "Nur spezifische Exceptions abfangen (kein except Exception ohne Grund)"
      - "Warnungen und Fehler mit logging.warning()/logging.error() melden"
      - "Keine print()- oder Debug-Ausgaben im Release"
      - "Fallbacks/Defaults für fehlende oder fehlerhafte Werte"
      - "Ressourcen (Sessions, Sockets) immer korrekt schließen (with/finally)"
      - "Fehlerausgaben mit Kontext (z.B. entity_id, user input)"
    documentation:
      - "README.md mit Installations- und Nutzungshinweisen"
      - "manifest.json: Dokumentationslink (documentation) vorhanden"
      - "Changelog pflegen, Breaking Changes hervorheben"
      - "Alle Konfigurationsoptionen dokumentieren (README, docstrings)"
      - "Bekannte Einschränkungen und Testhinweise dokumentieren"
    testability:
      - "Unit- und Integrationstests für alle Kernfunktionen"
      - "Tests für Konfigurationsvalidierung (voluptuous)"
      - "Test für alle Fehler- und Fallbackpfade"
      - "Komponenten sollen ohne echte Geräte testbar sein (Mocking, Fixtures)"
      - "Tests für Migrationen und Breaking Changes"
      - "Snapshot-Tests für Outputs, wo sinnvoll"
    maintainability_and_quality:
      - "Einfache, flache Modulstruktur, keine zyklischen Abhängigkeiten"
      - "Kommentare und Docstrings für alle Module, Klassen und komplexe Funktionen"
      - "Keine unnötigen Verschachtelungen oder komplexe Verzweigungen"
      - "Codeowners im manifest.json gesetzt"
      - "Verwendung von async/await und aktuellen HA-APIs"
      - "Keine deprecated Methoden oder Properties verwenden"
      - "Regelmäßige Tests mit neuen HA-Versionen"
      - "PRs und Issues im Repository dokumentieren"
    frontend_and_configflow:
      - "Config Flow (falls vorhanden) mit Validierung und Fallbacks"
      - "Frontend-Komponenten (falls vorhanden) auf Übersetzungen, Fehlerhandling und Responsivität testen"
      - "Konfigurationsoptionen im UI klar und verständlich präsentieren"
      - "Frontend- und Backend-Validierung konsistent"
      - "Benutzerführung und Fehlermeldungen klar und hilfreich"
    security_and_privacy:
      - "Keine sensiblen Daten loggen oder speichern"
      - "Secrets über secrets.yaml oder sichere Methoden einbinden"
      - "Alle Netzwerkkommunikation absichern (SSL/TLS, falls möglich)"
      - "Keine harten Zugangsdaten im Code"
      - "Überprüfung auf bekannte Sicherheitslücken in Abhängigkeiten"
      - "Keine ungesicherten Ports oder offenen Endpunkte"
      - "Daten nur so lange wie nötig speichern"
    performance:
      - "Keine blockierenden Aufrufe im Event-Loop"
      - "Async-Methoden für I/O verwenden"
      - "Daten nur so oft wie nötig abrufen"
      - "Cache und Throttling sinnvoll nutzen"
      - "Komponenten dürfen HA nicht verlangsamen"
      - "Speicher- und Ressourcenverbrauch prüfen"
    compatibility:
      - "Kompatibilität mit Home Assistant Core und Supervisor"
      - "Kompatibilität mit aktuellen Python-Versionen"
      - "Keine deprecated APIs oder Methoden verwenden"
      - "Regelmäßige Tests mit neuen HA-Releases"
      - "Abwärtskompatibilität zu älteren HA-Versionen (wo sinnvoll)"
      - "Manifest-Version aktuell halten"
