blueprint:
  name: Saisonale Rollladensteuerung (v4.30)
  description: |
    Robuste, minimalistische Version: Gruppen-Inputs werden direkt verwendet, keine Listenverarbeitung oder Duplikatlogik in Variablen. Logging zeigt Inputs direkt.
  domain: automation
  source_url: https://raw.githubusercontent.com/jard4101/blueprints/main/Seasonal_Blinds_Control.yaml
  author: jard4101

  input:
    group1_covers:
      name: Rollläden Gruppe 1
      selector:
        entity:
          domain: cover
          multiple: true
    group2_covers:
      name: Rollläden Gruppe 2
      selector:
        entity:
          domain: cover
          multiple: true
    group2_disable_switch:
      name: Deaktivierungsschalter
      selector:
        entity:
          domain: input_boolean
    spring_start:
      name: Frühlingsbeginn (TT-MM)
      default: "20-03"
      selector:
        text: {}
    summer_start:
      name: Sommerbeginn (TT-MM)
      default: "21-06"
      selector:
        text: {}
    autumn_start:
      name: Herbstbeginn (TT-MM)
      default: "23-09"
      selector:
        text: {}
    winter_open_time:
      name: Winter-Öffnungszeit
      default: "07:00"
      selector:
        time: {}
    spring_open_time:
      name: Frühling-Öffnungszeit
      default: "06:30"
      selector:
        time: {}
    summer_open_time:
      name: Sommer-Öffnungszeit
      default: "06:00"
      selector:
        time: {}
    enable_logging:
      name: Logging aktivieren
      default: false
      selector:
        boolean: {}

mode: parallel
max: 5
max_exceeded: silent

trigger:
  - platform: time_pattern
    minutes: "/1"
  - platform: state
    entity_id: sun.sun
    from: "below_horizon"
    to: "above_horizon"

action:
  - service: system_log.write
    data:
      message: |
        group1_covers={{ group1_covers }}
        group2_covers={{ group2_covers }}
        spring_open_time={{ spring_open_time }}
        summer_open_time={{ summer_open_time }}
        winter_open_time={{ winter_open_time }}
        group2_disable_switch={{ group2_disable_switch }}
      level: error

  - choose:
      - conditions: >
          {{ now().strftime('%H:%M') == spring_open_time }}
        sequence:
          - service: cover.open_cover
            target:
              entity_id: "{{ group1_covers }}"
            enabled: "{{ group1_covers|length > 0 }}"
          - service: cover.open_cover
            target:
              entity_id: "{{ group2_covers }}"
            enabled: >
              {{ group2_covers|length > 0 and is_state(group2_disable_switch, 'off') }}
          - service: system_log.write
            data:
              message: >
                Rollladen-Automation ausgelöst am {{ now().strftime('%d.%m.%Y %H:%M') }}
                Gruppe1: {{ group1_covers }}
                Gruppe2: {{ group2_covers }}
                Zeit: {{ spring_open_time }}
              level: info
            enabled: "{{ enable_logging }}"
