blueprint:
  name: Saisonale Rollladensteuerung (v4.6)
  description: |
    Automatische Steuerung von Rolll채den basierend auf Sonnenaufgang und Jahreszeiten.
    Unterst체tzt zwei Gruppen mit Deaktivierungsschalter und robustem Fehlerhandling.
  domain: automation
  source_url: https://raw.githubusercontent.com/jard4101/blueprints/main/Seasonal_Blinds_Control.yaml
  author: jard4101

  input:
    group1_covers:
      name: Rolll채den Gruppe 1
      selector:
        entity:
          domain: cover
          multiple: true
    # ... (alle anderen Inputs unver채ndert)

  triggers:
    - platform: time
      at: "{{ target_open_time }}"
    - platform: state
      entity_id: sun.sun
      from: "below_horizon"
      to: "above_horizon"

  action:
    - parallel:
        - service: cover.open_cover
          target: 
            entity_id: "{{ input.group1_covers | reject('in', input.group2_covers) }}"
        - service: cover.open_cover
          target: 
            entity_id: "{{ input.group2_covers | reject('in', input.group1_covers) }}"
