blueprint:
  name: Saisonale Rollladensteuerung (v4.8)
  description: |
    Automatische Steuerung von Rollläden mit optimierter Parallelverarbeitung.
    Behandelt Race Conditions und HA-Neustarts zuverlässig.
  domain: automation
  source_url: https://raw.githubusercontent.com/jard4101/blueprints/main/Seasonal_Blinds_Control.yaml
  author: jard4101

  input:
    # [Unveränderte Input-Definitionen]
    ...

variables:
  # [Zuvor definierte Variablen]
  ...

  # Erweiterte Fehlerbehandlung
  safe_open_time: >-
    {% if target_open_time is defined and target_open_time != "None" %}
      {{ target_open_time }}
    {% else %}
      {{ now().strftime('%H:%M') }}
    {% endif %}

triggers:
  - platform: time
    at: "{{ safe_open_time }}"
  - platform: event
    event_type: homeassistant_started

action:
  mode: queued
  max_exceeded: silent
  parallel:
    - choose:
        - conditions: "{{ input.group1_covers | length > 0 }}"
          sequence:
            - service: cover.open_cover
              target: 
                entity_id: "{{ input.group1_covers | reject('in', input.group2_covers) }}"
      default: []
    
    - choose:
        - conditions: >-
            {{ input.group2_covers | length > 0 
               and is_state(input.group2_disable_switch, 'off')
               and input.group2_disable_switch not in ['', None] }}
          sequence:
            - service: cover.open_cover
              target: 
                entity_id: "{{ input.group2_covers | reject('in', input.group1_covers) }}"
      default: []
    
    - service: system_log.write
      data:
        message: "{{ log_info }}"
        level: info
      enabled: "{{ input.enable_logging }}"
