blueprint:
  name: Saisonale Rollladensteuerung (v4.25)
  description: |
    Fehlerresistente saisonale Steuerung von Rollläden. Gruppen-Inputs werden korrekt als Listen behandelt und Duplikate garantiert entfernt.
  domain: automation
  source_url: https://raw.githubusercontent.com/jard4101/blueprints/main/Seasonal_Blinds_Control.yaml
  author: jard4101

  input:
    group1_covers:
      name: Rollläden Gruppe 1
      selector:
        entity:
          domain: cover
          multiple: true
    group2_covers:
      name: Rollläden Gruppe 2
      selector:
        entity:
          domain: cover
          multiple: true
    group2_disable_switch:
      name: Deaktivierungsschalter
      selector:
        entity:
          domain: input_boolean
    spring_start:
      name: Frühlingsbeginn (TT-MM)
      default: "20-03"
      selector:
        text: {}
    summer_start:
      name: Sommerbeginn (TT-MM)
      default: "21-06"
      selector:
        text: {}
    autumn_start:
      name: Herbstbeginn (TT-MM)
      default: "23-09"
      selector:
        text: {}
    winter_open_time:
      name: Winter-Öffnungszeit
      default: "07:00"
      selector:
        time: {}
    spring_open_time:
      name: Frühling-Öffnungszeit
      default: "06:30"
      selector:
        time: {}
    summer_open_time:
      name: Sommer-Öffnungszeit
      default: "06:00"
      selector:
        time: {}
    enable_logging:
      name: Logging aktivieren
      default: false
      selector:
        boolean: {}

mode: parallel
max: 5
max_exceeded: silent

trigger:
  - platform: time_pattern
    minutes: "/1"
  - platform: state
    entity_id: sun.sun
    from: "below_horizon"
    to: "above_horizon"

action:
  - variables:
      year: "{{ now().year }}"
      now_dt: "{{ now() }}"
      spring_date: "{{ spring_start if spring_start is defined and spring_start|regex_match('^(0[1-9]|1[0-9]|2[0-9]|3[0-1])-(0[1-9]|1[0-2])$') else '20-03' }}"
      summer_date: "{{ summer_start if summer_start is defined and summer_start|regex_match('^(0[1-9]|1[0-9]|2[0-9]|3[0-1])-(0[1-9]|1[0-2])$') else '21-06' }}"
      autumn_date: "{{ autumn_start if autumn_start is defined and autumn_start|regex_match('^(0[1-9]|1[0-9]|2[0-9]|3[0-1])-(0[1-9]|1[0-2])$') else '23-09' }}"
      rising: "{{ state_attr('sun.sun', 'next_rising') }}"
      safe_sunrise_dt: >-
        {% if rising is string %}
          {{ strptime(rising, '%Y-%m-%dT%H:%M:%S%z', now()) }}
        {% else %}
          {{ now().replace(hour=7, minute=0, second=0) }}
        {% endif %}
      sunrise: >-
        {% if safe_sunrise_dt is string %}
          07:00
        {% else %}
          {{ safe_sunrise_dt.strftime('%H:%M') }}
        {% endif %}
      spring_dt: "{{ strptime(spring_date ~ '-' ~ year, '%d-%m-%Y', now()) }}"
      summer_dt: "{{ strptime(summer_date ~ '-' ~ year, '%d-%m-%Y', now()) }}"
      autumn_dt: "{{ strptime(autumn_date ~ '-' ~ year, '%d-%m-%Y', now()) }}"
      now_ts: "{{ as_timestamp(now_dt) }}"
      spring_ts: "{{ as_timestamp(spring_dt, 0) }}"
      summer_ts: "{{ as_timestamp(summer_dt, 0) }}"
      autumn_ts: "{{ as_timestamp(autumn_dt, 0) }}"
      current_season: >-
        {% if now_ts >= spring_ts and now_ts < summer_ts %}spring
        {% elif now_ts >= summer_ts and now_ts < autumn_ts %}summer
        {% else %}winter{% endif %}
      season_times:
        spring: "{{ spring_open_time if spring_open_time else '06:30' }}"
        summer: "{{ summer_open_time if summer_open_time else '06:00' }}"
        winter: "{{ winter_open_time if winter_open_time else '07:00' }}"
      open_time: "{{ season_times[current_season] if current_season in season_times else '07:00' }}"
      target_open_time: "{{ [sunrise, open_time]|max }}"
      # Duplikate entfernen mit difference-Filter, Inputs als Listen
      final_group1: >
        {% set g1 = group1_covers if group1_covers is iterable else [] %}
        {% set g2 = group2_covers if group2_covers is iterable else [] %}
        {{ g1 | difference(g2) | list }}
      final_group2: >
        {% set g1 = group1_covers if group1_covers is iterable else [] %}
        {% set g2 = group2_covers if group2_covers is iterable else [] %}
        {{ g2 | difference(g1) | list }}
      group2_enabled: "{{ not is_state(group2_disable_switch, 'on') if group2_disable_switch else true }}"

  - service: system_log.write
    data:
      message: |
        [Rollladen-Blueprint] Variablen:
        spring_date={{ spring_date }},
        summer_date={{ summer_date }},
        autumn_date={{ autumn_date }},
        sunrise={{ sunrise }},
        current_season={{ current_season }},
        target_open_time={{ target_open_time }},
        final_group1={{ final_group1 }},
        final_group2={{ final_group2 }},
        group2_enabled={{ group2_enabled }}
      level: error

  - choose:
      - conditions: "{{ now().strftime('%H:%M') == target_open_time }}"
        sequence:
          - parallel:
              - service: cover.open_cover
                target:
                  entity_id: "{{ final_group1 }}"
                enabled: "{{ final_group1|length > 0 }}"
              - service: cover.open_cover
                target:
                  entity_id: "{{ final_group2 }}"
                enabled: "{{ final_group2|length > 0 and group2_enabled }}"
          - service: system_log.write
            data:
              message: >
                Rollladen-Automation ausgelöst am {{ now().strftime('%d.%m.%Y %H:%M') }}
                Gruppe1: {{ final_group1 }}
                Gruppe2: {{ final_group2 }}
                Saison: {{ current_season }}
                Sonnenaufgang: {{ sunrise }}
                Zielzeit: {{ target_open_time }}
              level: info
            enabled: "{{ enable_logging }}"
