blueprint:
  name: Saisonale Rollladensteuerung (v4.9)
  description: |
    Automatische Steuerung mit erweiterten Testszenarien, Sommerzeit-Handling und generischer Fehlerresilienz.
    Unterstützt zwei Gruppen mit Deaktivierungsschalter, queued-Modus für zuverlässige Ausführung und Logging.
  domain: automation
  source_url: https://raw.githubusercontent.com/jard4101/blueprints/main/Seasonal_Blinds_Control.yaml
  author: jard4101

  input:
    group1_covers:
      name: Rollläden Gruppe 1
      selector:
        entity:
          domain: cover
          multiple: true
    group2_covers:
      name: Rollläden Gruppe 2
      description: "Nur aktiv wenn Deaktivierungsschalter aus"
      selector:
        entity:
          domain: cover
          multiple: true
    group2_disable_switch:
      name: Deaktivierungsschalter
      selector:
        entity:
          domain: input_boolean
    spring_start:
      name: Frühlingsbeginn (TT-MM)
      default: "20-03"
      selector:
        text: {}
    summer_start:
      name: Sommerbeginn (TT-MM)
      default: "21-06"
      selector:
        text: {}
    autumn_start:
      name: Herbstbeginn (TT-MM)
      default: "23-09"
      selector:
        text: {}
    winter_open_time:
      name: Winter-Öffnungszeit
      default: "07:00"
      selector:
        time: {}
    spring_open_time:
      name: Frühling-Öffnungszeit
      default: "06:30"
      selector:
        time: {}
    summer_open_time:
      name: Sommer-Öffnungszeit
      default: "06:00"
      selector:
        time: {}
    enable_logging:
      name: Logging aktivieren
      default: false
      selector:
        boolean: {}

mode: queued
max_exceeded: silent

variables:
  # Sonnenaufgangszeit mit Fallback (bei HA-Neustart oder fehlendem Sensor)
  safe_sunrise: >-
    {% set rising = state_attr('sun.sun', 'next_rising') %}
    {{ as_local(rising) if rising else now().replace(hour=7, minute=0) }}

  # Validierte Datumseingaben (TT-MM)
  validated_dates: >-
    {% macro validate(date_str, default) -%}
      {% if date_str | regex_match('^([0-2][0-9]|3[0-1])-(0[1-9]|1[0-2])$') %}
        {{ date_str }}
      {% else %}
        {{ default }}
      {% endif %}
    {%- endmacro %}
    {
      "spring": "{{ validate(input.spring_start, '20-03') }}",
      "summer": "{{ validate(input.summer_start, '21-06') }}",
      "autumn": "{{ validate(input.autumn_start, '23-09') }}"
    }

  # Jahreszeitenlogik mit UTC-Handling
  current_season: >-
    {% set now_utc = as_timestamp(utcnow()) %}
    {% set spring_ts = as_timestamp(strptime(validated_dates.spring ~ '-' ~ now().year, '%d-%m-%Y')) %}
    {% set summer_ts = as_timestamp(strptime(validated_dates.summer ~ '-' ~ now().year, '%d-%m-%Y')) %}
    {% set autumn_ts = as_timestamp(strptime(validated_dates.autumn ~ '-' ~ now().year, '%d-%m-%Y')) %}
    {% if now_utc >= spring_ts and now_utc < summer_ts %}spring
    {% elif now_utc >= summer_ts and now_utc < autumn_ts %}summer
    {% else %}winter{% endif %}

  # Ziel-Öffnungszeit
  target_open_time: >-
    {% set season_times = {
      'spring': input.spring_open_time,
      'summer': input.summer_open_time,
      'winter': input.winter_open_time
    } %}
    {{ [safe_sunrise.strftime('%H:%M'), season_times[current_season]] | max }}

  # Duplikate filtern und leere Gruppen abfangen
  final_group1: >-
    {{ (input.group1_covers | default([])) | reject('in', input.group2_covers | default([])) | list }}
  final_group2: >-
    {{ (input.group2_covers | default([])) | reject('in', input.group1_covers | default([])) | list }}

  group2_enabled: >-
    {% if input.group2_disable_switch %}
      {{ not is_state(input.group2_disable_switch, 'on') }}
    {% else %}
      true
    {% endif %}

  log_info: >-
    Saisonale Rollladensteuerung:
    Datum: {{ now().strftime('%d.%m.%Y') }}
    Zeit: {{ now().strftime('%H:%M:%S') }}
    Jahreszeit: {{ current_season }}
    Sonnenaufgang: {{ safe_sunrise.strftime('%H:%M') }}
    Öffnungszeit: {{ target_open_time }}
    Gruppe 1: {{ final_group1 | join(', ') }}
    Gruppe 2: {{ final_group2 | join(', ') }}
    Gruppe 2 aktiviert: {{ group2_enabled }}

triggers:
  - platform: time
    at: "{{ target_open_time }}"
  - platform: event
    event_type: homeassistant_started

action:
  - parallel:
      - service: cover.open_cover
        target:
          entity_id: "{{ final_group1 }}"
        enabled: "{{ final_group1 | length > 0 }}"
      - service: cover.open_cover
        target:
          entity_id: "{{ final_group2 }}"
        enabled: "{{ (final_group2 | length > 0) and group2_enabled }}"
      - service: system_log.write
        data:
          message: "{{ log_info }}"
          level: info
        enabled: "{{ input.enable_logging }}"
